/**
	PROBLEM STATEMENT
	* Java Program To Find Even Fibonacci Numbers
	* Each New Term In The Fibonacci Sequence Is Generated By Adding The Previous Two Terms.
		By Starting With 1 And 2, The First 10 Terms Will Be,
			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	* By Considering The Terms In The Fibonacci Sequence Whose Values Do Not Exceed n, 
		Find The Sum Of The Even-Valued Terms.
	* Test Cases
		fiboEvenSum(10) should return a number.
		Your function should return an even value.
		Your function should sum the even-valued Fibonacci numbers: 
		fiboEvenSum(8) should return 10.
		fiboEvenSum(10) should return 10.
		fiboEvenSum(34) should return 44.
		fiboEvenSum(60) should return 44.
		fiboEvenSum(1000) should return 798.
		fiboEvenSum(100000) should return 60696.
		fiboEvenSum(4000000) should return 4613732.
	* @shenbaga-maharaja
	* Coded To Code
**/

import java.util.Scanner;

class EvenFibonacciNumbers{
	int sum(int number) {
		int a=1,b=2,s=0,t;
	  	for(b=2;b<=number;){
	    	if(b%2==0){
      			s+=b;
    		}
    		t=b;
    		b=a+b;
    		a=t;
  		}
	  	return s;
	  }

	public static void main(String[] args) {
		EvenFibonacciNumbers ob = new EvenFibonacciNumbers();
		Scanner ip = new Scanner(System.in);
		System.out.print(" Enter The Value :");
		int c=ip.nextInt();
		System.out.println(ob.sum(c));
	}
}


